# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b69502db48d009a5a30b4638910c8108f5dec0e06993cdbe9d27d9b465864d9c67e0a3bed02448ebd00a46bab22912f7a5f534333bca3f8d5a05a8ca7780b1b

test:
  secret_key_base: 1eeeef8b6d85342db60acda7117ea623f761e15b1db3407d69b885219fcdec95c0f973635c7f7a0bb83289931d5b1c06bc4854e2a6824a7700dd0625d804b248

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
